### ISSUE TITLE
Overeasy 1.6.6 latest ver does not show source info correctly

### ISSUE THREAD

**Issue by maveric69** [eggman19/eggman#6]
Latest updates in app and module caused addon to not show source detail for all found links. Goto live pd season 1 ep 4 as an example. It finds a bunch of links but the source detail is missing for 95% of the links. This was working fine before last few updates. I toggled the show source detail setting but no change.

**Comment by gateofgator** [comment]
Fixed

**Comment by eggman19** [comment]
Fixed

**Comment by maveric69** [comment]
Thanks for speed of fix!
